image: docker

services:
    - docker:dind

stages:
    - test
    - deploy

test:
    stage: test
    only:
      - master
    script:
      - echo tests performed successfully
step-production:
  stage: deploy
  before_script:
    - docker info
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base libffi-dev openssl-dev
    - pip install docker-compose    
  only:
    - master
  script:
    - docker-compose up -d --build
