stages:
    - test
    - deploy
test:
    stage: test
    only:
      - master
    script:
      - echo tests performed successfully
          
deploy:
    stage: deploy
    before_script:
    - echo "Before script...."
    - echo $SSH_PRIVATE_KEY
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
      - ssh -o “StrictHostKeyChecking=no” covid19@portal.camcann.com "cd api_management && git checkout master && git pull origin master && exit"
    only:
      - master
